"""
Download the Franka FR3 model from mujoco_menagerie and create the scene XML.

Run once before using the simulation:
    python simulation/setup_model.py
    python simulation/setup_model.py --force   # re-download
"""

from __future__ import annotations
import os
import sys
import shutil
import subprocess
import tempfile
from pathlib import Path

MODELS_DIR  = Path(__file__).parent / "models"
DEST_DIR    = MODELS_DIR / "franka_fr3"
# Scene XML lives INSIDE franka_fr3/ so meshdir="assets" resolves correctly
SCENE_XML   = DEST_DIR / "fr3_phri_scene.xml"

MENAGERIE_REPO = "https://github.com/google-deepmind/mujoco_menagerie.git"
SUBDIR         = "franka_fr3"


# ---------------------------------------------------------------------------
# Scene XML template (written after model download)
# ---------------------------------------------------------------------------

def _scene_xml(include_path: str) -> str:
    return f"""\
<!--
  FR3 pHRI Scene — generated by simulation/setup_model.py
  Placed inside franka_fr3/ so that meshdir="assets" in fr3.xml
  resolves to franka_fr3/assets/ correctly.
-->
<mujoco model="fr3_phri_scene">
  <include file="{include_path}"/>

  <worldbody>
    <!-- Desired EE target marker (green sphere) -->
    <site name="target_pos"   pos="0.4 0.0 0.5"  size="0.025"
          rgba="0 1 0 0.5" type="sphere"/>
    <!-- Human wrist position marker (red sphere) -->
    <site name="human_wrist"  pos="0.1 0.3 0.4"  size="0.025"
          rgba="1 0 0 0.5" type="sphere"/>
    <!-- Contact-detected indicator (yellow; toggled by Python) -->
    <site name="contact_flag" pos="0.4 0.0 0.7"  size="0.015"
          rgba="1 1 0 0.0" type="sphere"/>
  </worldbody>
</mujoco>
"""


# ---------------------------------------------------------------------------
# Download using git sparse-checkout  (downloads only franka_fr3/)
# ---------------------------------------------------------------------------

def _run(cmd: list[str], cwd=None, check=True):
    """Run a subprocess command and return (returncode, stdout, stderr)."""
    result = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True
    )
    if check and result.returncode != 0:
        raise RuntimeError(
            f"Command failed: {' '.join(cmd)}\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )
    return result


def download_with_git(force: bool = False):
    """
    Use git sparse-checkout to download only the franka_fr3 directory.
    This downloads ~5 MB of mesh files instead of the full ~500 MB zip.
    """
    if DEST_DIR.exists() and not force:
        print(f"[setup] Model already present at {DEST_DIR}")
        print(f"        Use --force to re-download.")
        return

    if shutil.which("git") is None:
        print("[setup] git not found. See manual instructions below.")
        _print_manual_instructions()
        sys.exit(1)

    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    print("[setup] Cloning franka_fr3 from mujoco_menagerie (sparse)…")
    print(f"        {MENAGERIE_REPO}")

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)

        # 1. Initialise an empty local repo
        _run(["git", "init"], cwd=tmp)
        _run(["git", "remote", "add", "origin", MENAGERIE_REPO], cwd=tmp)

        # 2. Configure sparse checkout BEFORE fetching blobs
        _run(["git", "config", "core.sparseCheckout", "true"], cwd=tmp)
        sparse_file = tmp / ".git" / "info" / "sparse-checkout"
        sparse_file.write_text(f"{SUBDIR}/\n")

        # 3. Fetch only the top commit (--depth 1) and only needed blobs
        print("[setup] Fetching (depth=1, blob:none filter)…")
        _run([
            "git", "fetch", "--depth=1",
            "--filter=blob:none",
            "origin", "main",
        ], cwd=tmp)

        # 4. Checkout only franka_fr3/
        print("[setup] Checking out franka_fr3/ blobs…")
        _run(["git", "checkout", "FETCH_HEAD"], cwd=tmp)

        # 5. Copy to our models/ directory
        src = tmp / SUBDIR
        if not src.exists():
            print(f"[setup] ERROR: '{SUBDIR}/' not found after sparse checkout.")
            sys.exit(1)

        if DEST_DIR.exists():
            shutil.rmtree(DEST_DIR)
        shutil.copytree(src, DEST_DIR)

    print(f"[setup] Extracted to {DEST_DIR}")


# ---------------------------------------------------------------------------
# Create scene XML
# ---------------------------------------------------------------------------

def write_scene_xml():
    """Write models/fr3_scene.xml that includes the downloaded FR3 model."""
    # Prefer scene.xml (menagerie provides floor + lighting), else fr3.xml.
    # Use filename-only paths since fr3_phri_scene.xml lives alongside them.
    if (DEST_DIR / "scene.xml").exists():
        include = "scene.xml"
    elif (DEST_DIR / "fr3.xml").exists():
        include = "fr3.xml"
    else:
        print("[setup] ERROR: Neither scene.xml nor fr3.xml found in downloaded model.")
        sys.exit(1)

    SCENE_XML.write_text(_scene_xml(include))
    print(f"[setup] Scene XML written → {SCENE_XML}")
    print(f"        (includes {include})")


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

def verify():
    """Load the scene in MuJoCo and print a brief summary."""
    import mujoco
    try:
        model = mujoco.MjModel.from_xml_path(str(SCENE_XML))
        data  = mujoco.MjData(model)
        mujoco.mj_forward(model, data)
        sites = [
            mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_SITE, i)
            for i in range(model.nsite)
        ]
        print(f"[setup] Verification OK — {model.nv} DOF, {model.nsite} sites")
        print(f"        Sites: {sites}")
    except Exception as exc:
        print(f"[setup] Verification FAILED: {exc}")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Manual instructions fallback
# ---------------------------------------------------------------------------

def _print_manual_instructions():
    print("""
Manual download (if git is unavailable):
    1. Go to https://github.com/google-deepmind/mujoco_menagerie
    2. Download the repository zip (Code → Download ZIP)
    3. Unzip and copy the franka_fr3/ folder into:
           pHRI/simulation/models/franka_fr3/
    4. Re-run:  python simulation/setup_model.py
""")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    force = "--force" in sys.argv
    download_with_git(force=force)
    write_scene_xml()
    verify()
    print("\n[setup] Done. Next steps:")
    print("    python simulation/run_simulation.py --mode data_check")
    print("    python simulation/run_simulation.py --mode impedance")
    print("    python simulation/run_simulation.py --mode phri")
